### ISSUE TITLE
Support numbers

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/filled-array#1]
What if I want an array with numbers :)?

**Comment by sindresorhus** [comment]
Yeah, not sure why I limited it to strings. It was what I needed right now. Fixed.

**Comment by SamVerschueren** [comment]
Actually, I found out `Array.prototype.fill` is an ES2015 feature. You could've made it a ponyfill. Allthough the implementation seems much more complex.

But I like as well the way it is ;).

**Comment by sindresorhus** [comment]
Yup, considered using that with a polyfill, but the resulting usage would have been ugly:

``` js
new Array(3).fill('foo');
```

Also, the polyfills are a lot slower as they do a lot of stuff which I didn't need.
